### ISSUE TITLE
Translate code comments

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#124]
The code examples contain a lot of important comments. It is important to translate these comments to other languages.
The translation software ignores code blocks, so we can not translate them.

What we could do is split up the code blocks and comment the code in normal text, and at the end add a link to the complete example (without comments).

**Comment by tyrannokapi** [comment]
Ideally, the best solution is to have examples that don't need to be split up. [This article](https://docs.spongepowered.org/en/plugins/message.html) is a good example of what I'm talking about - the examples are short, and there is an explanation for each example. Of course, there may be a few concepts that cannot be illustrated with a short example.

I don't think it would be a good idea to "split up" the code blocks, as you are suggesting. That would interrupt the flow of readability and would make future maintainability of the article a bit more difficult... not to mention that having several code blocks is also a bit messy.

And, we are trying to avoid repetition in the docs. Including the full example at the end of an article is repetitious, and makes future maintainability of that code a bit more difficult.

This is a valid point, though. Contributors should probably be discouraged from commenting in code blocks because of the inability to translate those comments.

**Comment by BlackGoat** [comment]
This will not be fixed, but the comments by @tyrannokapi will fit well in the Style guide.
