### ISSUE TITLE
Add section about WorldGenerators (or modifiers)

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#159]

**Comment by BlackGoat** [comment]
Can you clarify: is this is aimed at Server Ops or Plugin Devs? If the former, it can an extension of the fix for Parameters #95. WGen stuff for plugin devs probably belongs in plugin/advanced.

**Comment by boformer** [comment]
for plugin developers.

I don't know if the /sponge command supports world generators.

**Comment by boformer** [comment]
Some reference code: https://github.com/rutgerkok/SpongeGeneratorTest/tree/master/src/main/java/nl/rutgerkok/generatortest

**Comment by BlackGoat** [comment]
The World Management API needs a thorough explanation, when someone has the time and energy. It will make a world of difference ;)

**Comment by Deamon5550** [comment]
I'll see about about writing some things up on both world management and world generation once I've got the first phase of the world generation api implemented.

**Comment by Inscrutable** [comment]
What is the present status of this, @Deamon5550 ? It's been gathering dust here...

**Comment by Deamon5550** [comment]
Sorry I have been prioritizing what time I have to working on the implementation for world gen however I have started writing something up, it still needs a good bit of fleshing out as well as some supporting images and examples etc. but at least its words on paper. At some point some help reorganizing/rephrasing/rehashing would be appreciated as well since I've more or less just written this straight and I'm not exactly a pulitzer winner.

doc start https://gist.github.com/Deamon5550/db3b0666d50102bcd61d

Its lacking pieces on some custom pieces like genpop as that part of the api has not yet been written. Also the examples I have need working over as I just wrote them from memory not having a copy of the source in front of me right while I was writing.

Some other docs are in the javadocs of [WorldGeneratorModifier](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/gen/WorldGeneratorModifier.java) [Populator](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/gen/Populator.java) and [WorldGenerator](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/gen/WorldGenerator.java) as I have written quite extensively there in the past.

A final note is that I've written these based off of the contents of my branch feature/populators-phase1 (on all repos) if you're looking at the examples and getting rather confused thats probably the reason.
