### ISSUE TITLE
Add a list of all catalog types

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#185]
I think it would be useful to explain the usage of every catalog type, sorted by categories, maybe with a simple usage example.

This is a low-priority issue.

I opened this issue when I found out that the new Command API parses Catalog Types.

List: http://spongepowered.github.io/SpongeAPI/index.html?overview-summary.html

**Comment by BlackGoat** [comment]
Can we have a description of the issue please?

**Comment by boformer** [comment]
@BlackGoat of course :cookie:

**Comment by boformer** [comment]
We should also mention the GameRegistry.getType method and the catalogedElement command argument:

https://forums.spongepowered.org/t/solved-blocktype-from-id/7334

**Comment by Inscrutable** [comment]
Some more on Catalog Types from Gabizou: 
PLUGINS SHOULD AVOID USING STATIC REFERENCES FOR ANY CATALOG TYPE BASED STUFF
(because the plugin class gets loaded very early. Pre-init is very finicky). Texts can be started, but things other catalog types are not so easily done in pre_registry (eg. Item types).
