### ISSUE TITLE
Debugging skipping steps.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#260]
https://docs.spongepowered.org/en/plugin/advanced/debugging.html#intellij Says Open the Sponge(Vanilla) project.

This implies that the Sponge(Vanilla) project has already been downloaded from the git repository and loaded into IntelliJ by this point. In my opinion this is skipping several steps that should be listed, as well as how to import the project.

**Comment by saladoc** [comment]
No need for this imo since the guide
 - is in the `advanced` section
 - contains explicit references to required docs like the [How to set up your Workspace](https://docs.spongepowered.org/en/plugin/basics/workspace/index.html) page

There is no need to duplicate instructions that are already in the docs.

**Comment by ryantheleach** [comment]
I followed the How to set up your workspace guide, then went to the section on setting up debugging, I disagree that Debugging should be thought of as advanced, nor does How to set up your Workspace reference Sponge Vanilla.

**Comment by BlackGoat** [comment]
@ryantheleach is correct, the workspace setup only refers to SpongeAPI. Adding SpongeVanilla (or Sponge Coremod) does not feature on those pages.

**Comment by Nikecow** [comment]
I think this section can definitely use some work. I've been looking at it for hours but I can't figure out what steps I'm missing. It's way too condensed imo.
