### ISSUE TITLE
IntelliJ instructions incorrect

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#264]
Search for the official Sponge API Maven artifact under Search by artifact, and click Add.
Doing this only results in Spongeapi:1.0 being displayed in the list, either the newer versions of spongeapi need to be added to the default repositories, or alternate instructions need to be added on this page, https://docs.spongepowered.org/en/plugin/basics/workspace/idea.html#gradle

**Comment by simon816** [comment]
Possibly because the metadata has the tag `<version>1.0.0-SNAPSHOT</version>`?
http://repo.spongepowered.org/maven/org/spongepowered/spongeapi/maven-metadata.xml
@progwml6 Will know

**Comment by BlackGoat** [comment]
Is this still an issue, @ryantheleach ?

**Comment by ryantheleach** [comment]
Yes it's still an issue.

**Comment by ryantheleach** [comment]
http://puu.sh/jKwIY/20bc1e6bb0.png

**Comment by BlackGoat** [comment]
So that is the result? Paging @progwml6 can you do a fix? This issue is gathering cobwebs.
The offending page was recently moved to https://docs.spongepowered.org/en/plugin/workspace/idea.html
The correct tag should be on this linked page https://docs.spongepowered.org/en/plugin/workspace/dependencies.html so the alternative is to put that in by hand.

**Comment by Tzky** [comment]
Is this still unresolved? 
(looking at #336 )
