### ISSUE TITLE
Add British English

### ISSUE THREAD

**Issue by jamierocks** [SpongePowered/SpongeDocs#319]
Discussed https://korobi.io/network/esper/channel/lapis/logs/#L882-978

**Comment by ryantheleach** [comment]
Sorry, no logs are available for the requested date.

**Comment by Tzky** [comment]
I don't think a separation between A.E and B.E and even aussie english is necessary. This would just bloat the docs and make maintaining it even harder.

**Comment by BlackGoat** [comment]
Presently we seem to have Docs in a hybrid of British and American English, due to multiple international contributors. This results in some minor variations in spelling (-ise vs -ize etc) and some small grammatical issues (eg. do commas belong inside or outside of quotes?). It's not causing any issues in comprehension, and it would be a monster (and ongoing) edit to fix. I'd ignore it.

**Comment by RobertHerhold** [comment]
^
I don't think this is necessary at all. To me, it doesn't matter what locale/dialect of English the docs are written in; As long as it is comprehendible and fluent, it's fine.

**Comment by BlackGoat** [comment]
Translations of the Docs are exclusively the domain of CrowdIn now. Anyone who truly wants ethnic variations of English can pursue the matter there, if they want to maintain it too. Closing this.

**Comment by jamierocks** [comment]
In that case, could you add British English to the Crowdin?

**Comment by BlackGoat** [comment]
*sigh* Go wild.
