### ISSUE TITLE
Cleanup import statements in code examples

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeDocs#329]
Something I've run into is consistency across import statements... in a lot of cases, we end up writing the import statements in each code block, which leads to a lot of redundancy and honestly useless repetition (IMO). OR, the imports get put in some code blocks but not others. What does everyone think about declaring the most commonly used imports at the top/bottom of each page of documentation?

Another thing to consider is that most people (everyone?) uses an IDE that automatically imports classes, which really negates the need to include imports in code blocks.

Opinions?

EDIT: My personal opinion is that we could probably drop *most* import statements (maybe with the exception of the java 8 Optional rather than the Guice Optional)

**Comment by saladoc** [comment]
Our top priority on the docs must be clarity. So, if an import improves the clarity, it must stay. If it does not, it may be removed.As far as I am concerned, redundant import statements (read: If the exact same import is used in multiple code examples within the same page) may be removed. But everything else needs to be judged in the context of the code example. 

We must not forget that those code examples are not there to be compiled, but to be read. The "import" is not for a compiler, but for a reader. And few of the readers do have the whole classpath in their head. Imagine if you read `Keys` somewhere in a code example and cannot immediatly make sense of it, since the class name alone is not really descriptive and then look at the top (or at the top of the code example above) and see the class used is `org.spongepowered.api.data.keys.Keys`. You then can immediately link the `Keys` class to the data API. The Information is close to where it may be / is needed (namely within the code example itself) and therefore helpful and available. Contributors should aim to include the non-obvious imports at least on their first (prominent) occurance on a page.

Obvious imports (like almost everything java.util) should of course be left out.

**Comment by RobertHerhold** [comment]
Sounds good - I think we'll have to enforce this in another branch sometime - I'll leave this issue open until then.

**Comment by boformer** [comment]
Really short snippets should not include imports, but the package name should be mentioned before. 

But there are also more complex examples with 5+ imports. It is really convenient for the readers to copy/paste the import section instead of searching with their IDE.

Maybe very common imports like the Texts import could be omitted, but it would only save a single line.

**Comment by Inscrutable** [comment]
I ran the idea up the flagpole on the forums in [Quiz 8](https://forums.spongepowered.org/t/spongedocs-pop-quiz-8/9373). There is already some useful feedback.

**Comment by Inscrutable** [comment]
Gabizou had this to add (via Q8): "import statements should be fully qualified so that in the event the location of the class changes, people know to look at the docs for the changes.". Not binding, but another data point...

**Comment by RobertHerhold** [comment]
If there are no objections, I'm going to cleanup the imports in all of the docs so that import statements in code blocks are omitted if they have already been used previously in the page.

**Comment by ryantheleach** [comment]
Personally I think that any code snippets in the docs should be in a compilable plugin in the CookBook. Whenever the snippet stop's compiling because of a SpongeAPI Change, the update should be copied across to both the docs, and the CookBook.

However having to manually sync the two would cause duplication, and according to gratimax including snippets from a java repo using sphinx would be painful in some way?

But it would have the advantage of checking that the code works, when it breaks, and that people always have a full reference they can go to from each snippet.

**Comment by RobertHerhold** [comment]
I would ordinarily agree, but the majority of code blocks in the documentation are just as an example of what is possible, not necessarily something you would actually want to use in a plugin. I have no idea what would it would involve to reference code from the Cookbook in the docs, but I imagine it would be a pain to implement.

**Comment by Inscrutable** [comment]
Unless there is a volunteer that has the spare time and motivation to write plugins around these code snippets, this isn't going to happen. We have enough trouble finding Java-savvy folk just to write Docs. You could write this up as a separate issue @ryantheleach, but I don't see it getting much love anytime soon. It's not necessarily a bad idea, but it's a lot of extra work.

**Comment by boformer** [comment]
I don't see a benefit from removing import statements, and also no benefit from creating a plugin/unit tests at this point.

When the API is stable, packages and interfaces are not supposed to be changed.

And the import statements are not disrupting readability.

We can create a test plugin (basically just one class per code snippet) to check the code and import statements when the API reaches beta.
