### ISSUE TITLE
Progression of the API should not be reflected in the documentation

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeDocs#332]
Something I see quite often is that people writing documentation tend to touch on how the API was developed (i.e. "____ was a bit cumbersome, so ____ was developed"). I believe this is something that is completely irrelevant. The documentation should reflect the current function of the API, not mention how the API progresses... This is something I've been seeing more and more, and I think it would provide a lot more clarity and conciseness if it were left out.

Opinions?

**Comment by saladoc** [comment]
I understand that you are (among others, I suppose) referring to the Data Docs PR. I agree with you, basically the Information is not of interest. But I think I can also explain (at least for me) how it makes its way in the docs - in your own words: "Writing an introduction was a bit cumbersome, so a reference to the development process was used".

The docs are in a weird place between stern documentation and prose. Since the goal is not only to document (that's what javadocs are for) but also to introduce the reader to the API, we need more than just utter facts. And that's why we get into debates over wordings. In fact, what you're adressing is just that: A debate on style, in that case on introductory sentences. When looking for one, those little "that's how it came to be" facts is what naturally comes to the writer, since he has spent quite a time making himself familiar with the feature. In my case, I didn't even notice I was seeding excess information there until you pointed it out. To me it was just a sentence better than "Hey, we have Keys!". To be honest, I don't know if the sentence is now predominantly a distracting good-for-nothing information or a mere introductory sentence. It certainly was no information I deemed necessary for the reader to understand the data API.

I do not think such information should be included on purpose, but sometimes it comes to us not as "Fun Fact: We had to redo this because at first it sucked" but as a quirky way to introduce the page's topic. But that's why we review stuff and scrutinize every PR. So if you encounter information that seems unnecessary, imho the best way to react is to just add a line comment "Is this really necessary? I think it could be confusing" and have the author review the sentence and the information given.

Apart from https://github.com/SpongePowered/SpongeDocs/blob/saladoc/data/source/plugin/data/keys.rst, which other 'offenders' did you notice? This is the first time I'm aware of this.

**Comment by RobertHerhold** [comment]
*scratches head* I may have over-generalized... Now that I really think of it I can't really think of many other examples... 

To conclude, though, I see your point. I didn't mean to point fingers (although I did); I just wanted to bring attention to something that I thought prevented conciseness and clarity. Sometimes it's difficult for people from different stylistic backgrounds to have a consensus on how something should be written, but I'll try not to make unrealistic generalizations based on that.

**Comment by Inscrutable** [comment]
Just to add my $0.02, we take what we can get in documentation. Sometimes the author leaves it a bit fuzzy at the edges, poorly worded or somewhat off-topic. That's OK, it's what *we* are here for. I have amended and reworded quite a few docs to remove "fluff" and focus them. It would be great if every contributor presented us with a highly polished doc, but they may not be so proficient at English, nor writing user-facing docs. I'm just happy if they get the facts *right*, and clean up as needs be (and happy for others to clean up my boo-boos too).
