### ISSUE TITLE
Clarify that when working with ItemStacks, you're working with a copy

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeDocs#334]
For all events, API methods, etc. that return `ItemStack`s, they're all copies. No `ItemStack` is a live stack, ever. This needs to be well documented in the docs, specifically so that people working with the Data API and `ItemStack`s will know to set the changed `ItemStack` back to the inventory slot or to the event.

**Comment by Inscrutable** [comment]
So far, ItemStack is only mentioned here: https://github.com/SpongePowered/SpongeDocs/blob/1d5c6582e3798f8e09fc09bda70e5e2209e3a28b/source/plugin/items.rst

**Comment by saladoc** [comment]
Braindump:
This will have to be mentioned in the Inventory API docs #139 and maybe noted in a caveat on top of the items page. A mention on the Events page will probably be good as well: "Any `ItemStack` provided as a cause is only a copy; alterations to it will not affect any live data.".
Events and Inventories are the biggest offenders here, but some smaller occurences where an `ItemStack` is returned are scattered across the API (`Player#getItemInHand()` being a notable example). Since we don't have a plugin page about Players it might be hard to find a suitable location to mention this particular method, so I'm positive it will be best to just include a general warning on the Items page and leave the rest to the javadocs.  
On the Data API `ItemStackSnapshot` is used, so its clear from the different class that it is actually a copy. ItemStacks are afaik only used as a `DataHolder`, so I don't think an extra warning there is necessary.

**Comment by gabizou** [comment]
> Player#getItemInHand() being a notable example

This still returns a copy.

Everywhere in the implementation, we've been returning copies for a very long time.

**Comment by saladoc** [comment]
>> Player#getItemInHand() being a notable example

>This still returns a copy.

I know. I was merely making a List of where `ItemStack`s are returned
