### ISSUE TITLE
Language Support for SpongeDocs

### ISSUE THREAD

**Issue by BlackGoat** [SpongePowered/SpongeDocs#34]
Read-the-Docs defaults to the English version for the current pages. There are presently no non-english translations that I am aware of, we need to enable this so there *can* be some. How do we go about providing translated pages? Is there a plan somewhere?

**Comment by boformer** [comment]
Right now some changes made to the docs are not on transifex. Also, it seems like I can delete changes made by others, there are no restrictions.

Maybe a classic Wiki would be better for translation tasks.

**Comment by BlackGoat** [comment]
We don't have Transifex running at full efficiency yet. @gratimax may know more about how it's supposed to pull updates. The permissions for Reviewer state that "Once a translation is reviewed, it cannot be altered by a non-reviewer translator." so we probably need to fill those roles.

**Comment by boformer** [comment]
Reviewing works, but the docs version on Transifex is not up-to-date.
Many pages were changed and new pages were added, and we can't translate them.

**Comment by Dannyps** [comment]
Hi @boformer. I asked that same question to @gratimax a few weeks ago and he replied me [this] (https://forums.spongepowered.org/t/sponge-documentation-one-stop-shoppe/5296/29?u=dannyps). I believe nothing has changed since then. Anyway, I just mentioned him so he should see this and fill in the gaps. Moreover, I haven't yet seen the full recording of the stream so there might be something that has been announced on this subject that I'm not aware of.

**Comment by BlackGoat** [comment]
I brought up the issues of Transifex updates (and putting them online) in the SoS, but I have heard no definitive word on their resolution yet. This may need more devs thrown at it.
