### ISSUE TITLE
Document auto-save feature

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#503]
Blood recently added auto-saving (configurable!) for dedicated servers. We need to document that for API 4.1 as it's on master branch.

Commit with detailed description:
https://github.com/SpongePowered/SpongeCommon/commit/5afad37c96b825b9db7eb06cba52a02b4a856bea

**Comment by ryantheleach** [comment]
What he added was control over the default auto-saving that already happens in Minecraft.

By default Minecraft will periodically save loaded/open chunks, this allows you to disable that, or change the timing.

One thing I'm not 100% sure about, is whether the game saves in any other way. e.g. is the auto-saves also when the unloaded dirty chunks get saved? 
Or do they get cleaned up soon after unloading in order to make room in ram? 
Does changing the auto save period to 0 also disable the chunks that are being unloaded from saving?
Documentation on this aspect should cover how Minecrafts saving system works by default, how Sponge has modified it, and what the config settings do.

**Comment by bloodmc** [comment]
It only affects vanilla's autosave feature which is for "loaded" chunks and runs every 900 ticks(45 seconds) unless changed. Unloaded chunks will always save. I'll add a new config option to disable saving completely soon but it wont have anything to do with "autosave".

**Comment by Tzky** [comment]
Resolved with #509.
