### ISSUE TITLE
Bukkit and Sponge comparison spreadsheet is outdated

### ISSUE THREAD

**Issue by evilmidget38** [SpongePowered/SpongeDocs#517]
As I'm now starting up my first Sponge plugin, I found [this spreadsheet](https://docs.google.com/spreadsheets/d/1phlRmbPHCVhRIaZBi9xMjUuiDQkW-j8rSEV_tQnD47E/edit#gid=0) in the documentation.  Looking at it I actually almost gave up, as it makes it appear as if Sponge lacks a majority of the functionality available in Bukkit.  It looks like it was last updated for SpongeAPI 3, and I sort of suspect that even then it's not fully up to date for SpongeAPI 3.

The specific examples that I was looking for when I encountered this were the equivalent events for AsyncPlayerPreLoginEvent, and PlayerJoinEvent, which are equivalent to network.ClientConnectionEvent.Auth and network.ClientConnectionEvent.Join.

I'm actually willing to have a go at updating it if you'd like, as I'm going through the process of figuring out equivalents already.

**Comment by Deamon5550** [comment]
In my opinion that spreadsheet should not be linked from our docs, a class to class mapping is almost useless and really does give a bad view into what is in sponge. A new user of the api is far better off looking though the docs for concepts rather than direct api translations. There are only a few subsets of this class list that are actually useful such as the events.

**Comment by Tzky** [comment]
This list was never meant to be for a direct comparison of the two APIs. As you might have figured out by now Bukkit and SpongeAPI are fundamentally different, but are still sharing some equivalent events and some othe stuff. 

Of course Sponge is not lacking functionality when you compare it with Bukkit, but some things are way different and thus we just can't name a direct equivalent.

I also agree that this list might give new users a false impression on Sponge and its functionality and i'm considering the removal of the link myself. This list might fit better on the forums.

**Comment by Inscrutable** [comment]
What we really need is a series of tutorials to show how to re-implement bukkit things using SpongeAPI. That will take a lot of work, and may go stale relatively quickly until the API stabilises a bit (there's already an old issue for it too, #157 ). However, if no-one is getting practical use from this list, and it's out of date, then there's not much point having it on Docs for API 4.X onwards anyway. I'll let you chaps make the call on what to do with it, as I really have no idea how to gauge it's utility.

**Comment by 20zinnm** [comment]
@Inscrutable We were working on one (aniskywalker.com). It's not so much a direct transition as a "Plugin Tutorial" like Bukkit had.

**Comment by Inscrutable** [comment]
There has been some [feedback recently in support of the table](https://forums.spongepowered.org/t/sponge-status-update-25th-august-2016/14365/9?u=inscrutable), but unless there are volunteers to make it useful again it's still a dead duck.

**Comment by Inscrutable** [comment]
@evilmidget38 and @20zinnm if you want to resurrect the Sponge <-> Bukkit comparison table, step forward and make a PR. Otherwise, it will be gracefully retired very soon. It might be easier and more productive to help fill in missing docs explaining how to use the new SpongeAPI, as the differences between it and Bukkit now are acute.
