### ISSUE TITLE
Duplicated or deprecated HTML pages

### ISSUE THREAD

**Issue by ustc-zzzz** [SpongePowered/SpongeDocs#548]
I am a translator for the Chinese Simplified Translation of the SpongeDocs. I recently found that there are many duplicated or deprecated `.html` or `.po` pages in the docs, while they do not exist in the GitHub repo. 

Here is a screenshot for the [Chinese Simplified Translation page](https://translate.spongepowered.org/project/sponge-docs/zh-CN#):
![screenshot](https://cloud.githubusercontent.com/assets/8004211/20076368/200ce218-a573-11e6-93ff-e18c1b276d80.png)
And here is a screenshot for the [GitHub repo](https://github.com/SpongePowered/SpongeDocs/tree/master/source/plugin):
![screenshot](https://cloud.githubusercontent.com/assets/8004211/20076465/712b1fca-a573-11e6-9ac6-074dba845526.png)

There are `.po` files which should not exist in the translate pages. Furthermore, the corresponding HTML pages are available(such as <https://docs.spongepowered.org/master/en/plugin/messagechannels.html>). 

Therefore, maybe there could be some additions on build scripts so that there wouldn't be any useless pages in the SpongeDocs.

**Comment by Inscrutable** [comment]
Sometimes the older translated pages may be useful to provide suggested translations for the new pages, but they have no use beyond that. This issue has come up before (as #150). We may need to either manually crop older .po files, or try developing some sort of script to crop the redundant ones. Any suggestions, @Tzky @ryantheleach ?

**Comment by Tzky** [comment]
First and foremost: thanks for translating our docs into chinese!

We're aware that Crowdin is hosting older (now unused) files. However simply deleting them isn't as easy as it might sound. We'd have to manage that on our end and just tell Crowdin which files we want to remove from our translation. We can't delete everything and upload just the most current files, as Crowdin will delete all files *and* their corresponding translations.

The current state of this issue is that a staff member manually collects and deletes unused files from time to time. Usually when one of the translators opens an issue and requests it, like you just did. That being said, i'll look into this and remove unused, old files :)
