### ISSUE TITLE
Request for official approval for the Chinese Simplified translation, the contributor list, and the build frequency

### ISSUE THREAD

**Issue by ustc-zzzz** [SpongePowered/SpongeDocs#555]
As a translator for the Chinese Simplified translation, I hope to make the translation project widely known in one of the largest forum about Minecraft in China, MCBBS (<http://www.mcbbs.net/>), and I have published a post (<http://www.mcbbs.net/thread-647066-1-1.html>, you could find a large Spongie at the beginning of the post XD). For confirmation, MCBBS requires a relatively formal official approval that the official team allows MCBBS to publicize the project as "the Chinese Simplified translation agreed and supported by the official development team". The screenshot of the reply will be sent to the managers of MCBBS to emphasize that the translation is official and it is not invalid.

Besides, in order to decide the award by the works of the contributors respectively, The managers of MCBBS needs a contribution list for the Chinese Simplified translation. Maybe I could write scripts to collect the contribution list, but it is unofficial and thus not so credible (because I am also a contributor who could be awarded XD). So I would like to know if there is a way to provide official contribution list which shows how many words were translated by each translator. It could be better that the contributor list could be updated with the progress of the translation because the SpongeDocs itself is also updated continuously. Furthermore, I world like to be a proofreader of the Chinese Simplified translation if possible because of the potential quality reduction with the rising number of contributors.

What's more, I believe that more and more Chinese Minecraft lovers will take part in the translation of SpongeDocs with the spread in MCBBS (and in fact it has already been increasing for several weeks XD), so I request for more frequent builds such as nightly build or two or three times a week (it will help us a lot because we could also make spelling mistakes and it's difficult for us to find them until it builds XD).

Thanks for your reading.

**Comment by Inscrutable** [comment]
First up (I also replied on CrowdIn), I have elevated @ustc-zzzz to proofreader on Chinese (Simplified). We shall see if that provides sufficient access to translator stats (CrowdIn help pages weren't as helpful as I'd like), as they *are* available to admins, with a bit of rummaging.
The frequency of SpongeDocs builds (and also translations) is tied to GitHub activity - when a PR is merged, a new Docs build is triggered. We'd have to automate it somehow to make it more frequent - or get more editors. Sometimes activity slows down a bit, and no new builds happen for a week or more.
Input and ideas always welcome.

**Comment by ustc-zzzz** [comment]
Thanks a lot! Those related pages are available for proofreaders so it is enough for me to collect the translator stats and the identity of a proofreader and this issue are enough to prove that I have contact with the official development team.

**Comment by ST-DDT** [comment]
IMO nightly-builds are probably a good choice. As an alternative/addition we could add the ability to Spongie in IRC to trigger these builds when she is asked to do it by authorized users. (Magic chant: abracadabra nova docs constructicus...)
The second option will also help us to bring more activity to IRC and thus gives everyone easier access to help as well as awareness on possible issues with the documentation.

**Comment by Inscrutable** [comment]
I've talked to @Minecrell about this, as there is a nascent plan to migrate to our own Jenkins instance. Another possibility is to decouple translation builds from Docs, so they can build on their own. This is one of many things that need to be considered if/when we move away from using Travis ...

**Comment by progwml6** [comment]
the entire build system for docs needs to be redone at some point to simplify it, however that's partially tied into some work that is ongoing with moving some of the theme components to use templates that are easier to share with some of our other repos

**Comment by h404bi** [comment]
glad to see that the Chinese Simplified translation of SpongeDocs active again, thanks to those who have made contribution.

while talking about the docs builds, I personally agree with "decouple translation builds from Docs". But I want to talk more.

I joined in the Chinese Simplified translation activity since June 2015. And have witnessed the development of SpongeDocs, from v3.1.0 to v5.0.0. In the past year, only few people was translating the docs, but the docs update frequently.

I experienced the breaking changes of the docs, too many new sentences to be translated. and many translated sentences marked back to untranslated after corresponding original sentences update. This affect the translation build, I saw some sentences change back to English (when I was translating v3.1.0).

I hate that translators have to update the translation to ensure it keep translated while every single original SpongeDocs update, even if there only one word different. sometimes I think why can't we make translation builds separated from the main's: target a specific commit, translate all sentences, make a translation build based on the specific commit and release to public. then merge updates from upstream, target a specific commit again, update the translation, then make build and release.

recently I fork the SpongeDocs, and do translation on my own fork<sup>[1]</sup>. I can make stable translation builds (based on a specific commit) even if upstream update frequently. it's a old version of the docs, but the idea I want to express is common.

SpongeDocs is huge, but only few people are translating. too unstable translation builds make translators (at least, me) lost motivation. And that's user unfriendly some sentences change back to untranslated while a new SpongeDocs build is triggered.

thanks to @ustc-zzzz to make Chinese Simplified translation active again. now I think I can go back to the official translation group if there are more translators join in the activity. and it's time to elect proofreaders.

[1]: https://github.com/h404bi/SpongeDocs-CN/issues/1

**Comment by Inscrutable** [comment]
I believe most of the issues raised here have since been resolved (or become outdated). SpongeDocs is still only built when PR's are merged, although I can trigger a build whenever required. 
We can commiserate with translators having trouble keeping up; it's difficult for us to keep up with API changes, too. ;)
