### ISSUE TITLE
API 6.0 and retirement of API 3.X docs

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#601]
With the release of API 6.0, we no longer have the capacity to support <s>or host</s> the old API 3.X docs. We only want to offer three versions, to reduce load on Crowdin and shorten docs build times. Our agreed solution is to bundle the 3.X docs into a _pdf_ or _html_ file and offer that. At that point we can retire the 3.X branch and focus on versions 4, 5 and 6.

So, we need to (1) tweak the SpongeDocs to make a new branch for 6.1.0, including updating the sponge.conf file etc, <s>and (2) sort out publishing the finalised 3.X docs. A new docs page for these links would be reasonable, "Legacy versions", or maybe the "Sponge Retirement Home for Bewildered APIs".</s>
Any help or suggestions would be appreciated. @Tzky @12AwsomeMan34 @RobertHerhold @ST-DDT @ZephireNZ @saladoc @Minecrell

**Comment by Minecrell** [comment]
> With the release of API 6.0, we no longer have the capacity to support or host the old API 3.X docs. 

Supporting it might be indeed a problem: theme changes need to be applied for all old docs and they take up a lot of strings on Crowdin. However, the hosting isn't any problem. We can just stop building them and keep them on our website the way they are, the additional old files don't require any maintenance.

We already have the ZIP downloads for all our versions so that should be covered as well. We could consider hiding/marking them in the versions list in a special way, because otherwise the version list would just grow with every version change.
