### ISSUE TITLE
Silent Gems - Dupe Bug - Sponge Issue

### ISSUE THREAD

**Issue by Keaton1188** [SpongePowered/SpongeDocs#632]
Hi there, I have noticed a dupe bug with the Chaos Altar, this dupe bug does NOT happen on single player so guessing its an issue with sponge.

What you do - Place down the Chaos Alter, put any item in it and break it with a pickaxe, the item that you put in it will double when you break the Altar.

FTB Horizons 3 - Newest Version (1.0.0)

SpongeForge:
Minecraft: 1.12.2
SpongeAPI: 7.0.0-SNAPSHOT-bb567e4
SpongeForge: 1.12.2-2503-7.0.0-BETA-2708
Minecraft Forge: 14.23.0.2515

**Comment by ryantheleach** [comment]
@Keaton1188 Thanks for the report!

Unfortunately this issue will be closed as soon as someone with access see's it.

This repository / issue tracker is reserved for issues pertaining to Sponges documentation, docs.spongepwered.org

For future reference, we have 4 'dev' repositories that accept tickets.

https://github.com/SpongePowered/SpongeAPI
https://github.com/SpongePowered/SpongeCommon
https://github.com/SpongePowered/SpongeForge
https://github.com/SpongePowered/SpongeVanilla

**API** - Post tickets relating to API design / confusion or JavaDoc usage.

**Common** - Post tickets relating to bugs / features relating to BOTH SpongeVanilla / SpongeForge

**SpongeVanilla** - Post tickets that relating to bugs / features that only occur on the SpongeVanilla server.

**SpongeForge** - Post tickets that relate to bugs / features / mod incompatibilities, as mod support generally is an issue that relates to SpongeForge. occasionally things will be fixed in SpongeCommon that affect only SpongeForge, but that doesn't stop the ticket only being relevent to forge.

I hope this makes sense.

**Comment by Keaton1188** [comment]
My bad! Thank you.
