### ISSUE TITLE
Brief Tutorial on Logging?

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeDocs#644]
Would a brief tutorial in log4j2 logging configuration be in scope? Who do we have that has decent knowledge of log4j2 that could contribute an article?

Related: https://github.com/SpongePowered/SpongeDocs/issues/627

05:20 | <⇅k​i​l​l​j​o​y​> | use a log4j2.xml
-- | -- | --
05:22 | <⇅k​i​l​l​j​o​y​> | https://logging.apache.org/log4j/2.x/manual/configuration.html
05:23 | <⇅k​i​l​l​j​o​y​> | launch the server with -Dlog4j.configurationFile=my-log4j2.xml

**Comment by phit** [comment]
this is broken on 1.12 forge fyi

**Comment by JBYoshi** [comment]
I thought Sponge uses slf4j?

**Comment by kinggoesgaming** [comment]
Yes sponge uses slf4j but it's just abstraction over a real logging framework so that if the logging framework is changed in the future, if slf4j supports it developers don't have change their code to adapt

**Comment by uglycoyote** [comment]
The "Logging and Debugging" page seems to have sufficient detail about how to inject the logging framework and to use it.  

I think it would be helpful just to add a sentence or two explaining where to **find** the log messages, which was not obvious to me initially.  (I expected that the server output visible in the terminal would contain my log statement, but it did not.  I later found it by grepping in the logs directory, so it seem that more detailed debug logging only goes to files -- or maybe there's a verbose option for the server to run in where it prints them to console?) 

It might also help to include a log-print into the sample on the Main Plugin Class page, just because a log print makes a good first step in testing that your project works.   The full details about logging belong in their own section, but having a quick "getting started" logging example early in the docs would be great for the user trying to get things set up for the first time.

**Comment by Inscrutable** [comment]
These are very useful suggestions, thanks. You might have saved yourself some typing by just making this as a PR too - we'd be happy to review and merge it, if you're up to making a contribution.

**Comment by uglycoyote** [comment]
@Inscrutable less typing perhaps, though I'm not confident that I have the complete/correct details for quality documentation. I'll research a bit further and try making a pull request.  Thanks.
