### ISSUE TITLE
Explain dependency injection and modularization

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeDocs#67]
I think Sponge plugins have to use dependency injection to get the game object or the plugin logger (what else?).

We have to explain that.

Also, we should explain how to outsource parts of your plugin to other classes (pass plugin and logger object)

**Comment by ryantheleach** [comment]
You can also get it passed in some of the state events.

**Comment by modwizcode** [comment]
Will get this today

**Comment by boformer** [comment]
@ryantheleach That's right, but not the logger and not the recommended config file/directory

**Comment by BlackGoat** [comment]
*nudge* @modwizcode the Advanced Topic "dependency-injection" still awaits creation...

**Comment by modwizcode** [comment]
Ah yes, I'll look at that today.

**Comment by modwizcode** [comment]
Got a semi-useful placeholder which can be updated by me when I've got more time, or someone else if they'd like.

**Comment by simon816** [comment]
It should be one of the first things plugin developers see, how to get the game instance. I've seen in several places people asking "How do I get this 'game' object?" etc. and because dependency injections are preferred, the example should be an `@Inject Game...`.

**Comment by modwizcode** [comment]
@simon816 Hmm did I forget that example?

**Comment by simon816** [comment]
The [page is temporary](https://docs.spongepowered.org/en/plugin/advanced/injection.html) at the moment, there's no examples (from what I can tell).
But because the Game object is fundamental to a lot of sponge related APIs, getting an instance of it shouldn't be tucked away under advanced at the bottom of the ToC. Well, maybe an in-depth explanation of dep injection could be under the advanced category, but for simple usage to obtain the Game, it should be clearly visible.

**Comment by modwizcode** [comment]
Yeah I was thinking about that myself. An intro on getting the top 3-4 injections should be given in the beginning.

**Comment by BlackGoat** [comment]
The page has been [updated](https://docs.spongepowered.org/en/plugin/basics/injection.html) so I'm closing this issue. If you have any more examples to add @modwizcode , go ahead.
