### ISSUE TITLE
Transition from ide-specific plugin setup to using gradle/maven

### ISSUE THREAD

**Issue by gratimax** [SpongePowered/SpongeDocs#69]
Not to pick on anyone, but here's a conversation that happened in #dev:

![conv](http://puu.sh/f6Jc5/946118815e.png)

The tutorials on setting up IDEs should lead up directly into using gradle/maven, most likely with a recommendation to use gradle(for ForgeGradle)

**Comment by AbrarSyed** [comment]
Now if anyone volunteers to make a ForgeGadle eclips/eidea pligun.. I am more than willing to help..

**Comment by BlackGoat** [comment]
The page at source/plugins/workspace.rst goes through from JDK to IDE to BuildScript with Gradle / Maven. It is not very wordy, and probably needs more explanatory text. We could also add appropriate links to the IDE pages at the bottom, so they can be kept in sequence.

**Comment by tyrannokapi** [comment]
I think it's best to approach this from a UX perspective, as the problem with that IRC conversation seems to be in how the information in the docs is presented. The necessary information is (mostly) there.

At the moment, the tutorial for writing plugins follows this outline:

- Installing the JDK
- IntelliJ Idea
  - Download
  - Plugins (does this need to be included?)
  - Gradle integration
  - Git integration
- Eclipse
  - Download
  - Plugins (does this need to be included?)
  - Gradle integration
  - Git integration
- NetBeans
  - There's just a warning on this page
- Gradle dependencies
- Maven dependencies
- Writing a plugin
- Installing the Java Development Kit
  - Download
  - Correct Java version for your computer

The main problem I see with that approach is that users are given the same information twice (and it's pretty safe to assume that users will be clicking the "Next" button on the bottom of each page, rather than using the Table of Contents). There aren't IDE-specific instructions for setting up Gradle and Maven; and even if there were, the instructions would be separated from the IDE page in this approach.

Also, it's a bit odd for the page about installing the JDK to be after "Writing a plugin."

Instead, I think the following approach may be easier for users to follow, particularly ones who are just starting out with plugin development:

- Installing the JDK
  - Recommend Java 7 because Java 6 is EOL'd, and Java 8 is still rather new
  - Give basic steps on how to download and install
  - At the bottom, link to "I want to use IntelliJ Idea" or "I want to use Eclipse"
- Starting with an IDE
  - IntelliJ Idea
    - Download
    - Setting up Gradle in IntelliJ (recommend)
    - Setting up Maven in IntelliJ
    - Git integration
  - Eclipse
    - Download
    - Setting up Gradle in Eclipse (recommend)
    - Setting up Maven in Eclipse
    - Git integration
  - NetBeans
    - Do we really want to recommend this as an option at the current time?
- Writing a plugin

This approach essentially offers the instructions on a per-IDE basis, rather than generalizing things. Sure, some information (like Gradle and Maven dependencies) may be repeated; but in the grand scheme of things, it is better to have a little repetition than to confuse people. Plus, I think it's fair enough to put a warning on top of the IntelliJ and Eclipse pages saying "The instructions on this page apply to X IDE."

This approach also squashes per-IDE instructions into one page each, which helps solve the problem of sequential ordering. And, there are actually 3 less pages with this approach (4 less if we leave NetBeans out).

Anyways, just my opinion. I can help out with writing the pages.

**Comment by BlackGoat** [comment]
This also relates to #58 where there was an evolving plan for a shared "Tools" folder. @boformer may have some opinions on this.
One of the problems here stems from the "next" buttons on RtD basically going through the folder in alphabetical order, hence my suggestion of links at the bottom.
Repetition of some info isn't a problem, and it's easy for the translators to handle, but It IS a pest to maintain when an update affects it, so try to future-proof it if you can. It will make this boondoggle easier to navigate for users and us, at the expense of some bloat, so I won't complain.
The javadevkit page *does* warn against Java 6 and 8, maybe you can make that clearer.
As for NetBeans, we *aren't* recommending it, but it's inclusion was requested by several folk. It's really up to them to fill that page in, as it's rarer here than the other IDEs. We don't want to exclude people without good reason.
Go ahead, make my day. ;)

**Comment by tyrannokapi** [comment]
Okay, I'll see what I can throw together once I finish editing my friend's book - probably later today. 

I'll try to keep repetition to a minimum. If anything, I think the Maven and Gradle information is the only thing that may be affected by an update. I'll add links to the bottom of the pages too so we can see how that works out.

**Comment by progwml6** [comment]
@BlackGoat java versioning reccomendations need to be discussed with developers as a large portion of us are using java 8 right now

**Comment by tyrannokapi** [comment]
The recommendation for Java 7 is made for plugin developers, as most (shared) server hosts do not yet support Java 8. Developing plugins with Java 7 ensures that plugins are available to more server owners.

If Java 8 is encouraged for Sponge development, perhaps that could be noted on ``/devs/forge/contributing``. But, as the JDK page is shared between the plugin development and Sponge development tracks, I think it's best to keep the recommendation for Java 7 on there until more shared server hosts support Java 8.

**Comment by progwml6** [comment]
@tyrannokapi the version you compile against and what is installed are 2 VERY different things...
as java 7 is supposed to be EOL'd in april java 8 should probably be the recommendation for the version to  install
iirc we recommend compiling plugins against java 6 which is what mojang compiles minecraft against.

**Comment by tyrannokapi** [comment]
Ah, I misunderstood what you were trying to say before. I thought you were implying that plugins should be compiled against Java 8. My bad.

On that note, yes, Java 8 probably should be the recommendation to install. The problem is explaining the difference between what is installed and what you compile plugins against, in terms that anybody could understand (hence the single recommendation currently in the docs). That can be worked out though.

Personally I feel that it's probably okay to recommend compiling against Java 7, but if Java 6 is preferred for the purpose, that can certainly be changed.

**Comment by BlackGoat** [comment]
Compiling against Java 6 will at least eliminate the minor:major version error that often occurs when Java 7-built plugins are used in Java 6, but it's insecure because it is EOL'd. I had heard Mojang wanted to make the move to Java 8 with their new launcher, when they do that this should all be academic. I guess we have to go retro until that time.

**Comment by ryantheleach** [comment]
If you are encouraging users to have a different JDK installed then what they are compiling to, maybe something like animal-sniffer would be useful to mention. http://mojo.codehaus.org/animal-sniffer-maven-plugin/
