### ISSUE TITLE
Guidance on appropriate choice of version number for new plugins

### ISSUE THREAD

**Issue by uglycoyote** [SpongePowered/SpongeDocs#727]
In pull request #725, a discussion came up around the instructions (on the IDEA page) about what to use when the IDE prompts you for a version number for your newly created project.  Currently the instructional text in the Sponge docs just says it is up to you.

If there is a standard for what kind of version numbering scheme we want Sponge plugins to use, it would be good to clarify this here (though maybe it should be a page in its own because it is not an issue specific to IDEA and one will have to decide on a version number regardless of the choice of IDE our abstinence from one.

I don't personally know what the right answer is.  I am aware of "semantic versioning" which is something like:

 - change the first number when you make a breaking change to the API
- change the middle number when you add new functionality to the API.
- change the last number for any other minor changes

This might not totally fit with plugins which don't have an externally facing API

**Comment by ST-DDT** [comment]
I would recommend plugin users one of the following versioning schemes:

* Semver (same as you described above)
* Simple versioning (rewrite.update)
  (Because you usually don't have that many releases and you usually don't expose an API)
  * For every rewrite or big change increase the first version number
  * For every other update/feature/bugfix increase the second version number)
