### ISSUE TITLE
A TypeToken for Text exists, but Text is not listed on Configuration Nodes page

### ISSUE THREAD

**Issue by benjaminmordaunt** [SpongePowered/SpongeDocs#735]
![image](https://user-images.githubusercontent.com/17656637/43718852-df411720-9983-11e8-8ffd-dd49409ed0e4.png)

The Configuring Plugins -> Configuration Nodes page doesn't list `Text` in the list above, nor under Basic Types, despite a TypeToken existing for it.

**Comment by ryantheleach** [comment]
To add on to this, I think we should provide a little best practice in regards to Text.

Which text serialization format does SpongeAPI use in Configurate by default?

Which should you use for your plugin?

How do you override this choice in your plugin for your configurations, or should you use string's and handle serialization yourself?

**Comment by ST-DDT** [comment]
👁 👁 
==

**Comment by ST-DDT** [comment]
**Ref:**

* https://docs.spongepowered.org/stable/en/plugin/configuration/index.html
* https://docs.spongepowered.org/stable/en/plugin/configuration/nodes.html#de-serialization

**Issues:**

* [ ] Mention [`TypeTokens`](https://github.com/SpongePowered/SpongeAPI/blob/stable-7/src/main/java/org/spongepowered/api/util/TypeTokens.java) which contains already existing type tokens and mention that the user should possibly should use a similar approach if he has multiple type tokens itself.
* [ ] Find out which types have serializers registered by default (any of the above?)
  * http://configurate.aoeu.xyz/wiki/Object-Mapper.html
  * ``Set``s? is the order retained? sorted?
* [ ] Which ~text~ serialization format does SpongeAPI use in Configurate by default?
  * Hocon is mentioned multiple times
  * Maybe mention it on the loaders page again
  * Stronger links between config and [Text Serializers](https://docs.spongepowered.org/stable/en/plugin/text/representations/index.html)
* [ ] Which should you use for your plugin?
  * Sponge recommends hocon (Mentioned on the index page)
  * Maybe mention it on the loaders page again
* [ ] How do you override this choice in your plugin for your configurations, or should you use string's and handle serialization yourself?
  * YAML is mentioned, but Gson is not.
  * Needs an example (loaders page)
* [ ] Add a full example of loading and saving a `@ConfigSerializable` instance to [Using Objectmappers](https://docs.spongepowered.org/stable/en/plugin/configuration/serialization.html#using-objectmappers).
  * Mention the implications of not using `@Setting` on a field
  * How to use default values
  * What happens if new values are added/are missing in the config file
* [ ] Expand the example regarding the usage of defaults.
  * How do you actually merge the configs
  * How are/should partial default defaults handled
* [ ] Explain when the config should be saved (for the first time)

--------------------------------

@ryantheleach Are you going to add these or shall I take over? Is anything missing in my list?

@SpongePowered/developers What is the recommended way of serializing Text: via Config, inline json, extra Json files (per entry?), or via minecraft lang files? Or don't we provide a recommendation until the TextTemplates have been [improved](https://github.com/SpongePowered/SpongeAPI/issues/1891)?

**Comment by ryantheleach** [comment]
@ST-DDT Go for it, the questions I had were largely open ended, that I didn't yet have answers for, and would need to investigate anyway.
