### ISSUE TITLE
Changes coming to Versioning

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeDocs#768]
We'll need to update the versioning page to deprecate the older Legacy system and add the new one when this PR goes live. Perhaps we can include some version of the tables there too.

https://github.com/SpongePowered/SpongeForge/issues/2367

**Comment by ST-DDT** [comment]
This link contains some explanations that might help writing the docs: https://forums.spongepowered.org/t/sponge-status-update-10th-october-2018/25777

**Comment by LordRalex** [comment]
The only page where I find the version references is on this page:
https://docs.spongepowered.org/stable/en/server/getting-started/implementations/spongeforge.html

Would it make more sense to have a dedicated version page that explained the format and have the install page reference that?

**Comment by ST-DDT** [comment]
That is planned (as part of this issue). Maybe the info will be added to https://docs.spongepowered.org/stable/en/plugin/api-versions.html , but that is not sure. Or do you have a suggestion for an alternative location?

**Comment by LordRalex** [comment]
That page would make the most sense, but the current dropdown location for it doesn't. I didn't find it because it's under a section I would not have thought to look. It also does really read more for development, so to me, it'd make sense to tailor it more as a general understanding of how the versions work and how to read it. Then the create and install pages can reference it directly. You don't see that page unless you click into the "Creating a Plugin" which for server administration, doesn't matter.

**Comment by Grauldon** [comment]
The following pages also need updating:

- [https://docs.spongepowered.org/stable/en/contributing/versioning.html](https://docs.spongepowered.org/stable/en/contributing/versioning.html) 
- [https://docs.spongepowered.org/stable/en/plugin/internals/implementation.html](https://docs.spongepowered.org/stable/en/plugin/internals/implementation.html)

Here is a list of **all** the files that need to be changed:

source/server/getting-started/implementations/spongeforge.rst
source/plugin/api-versions.rst
source/plugin/internals/implementation.rst
source/contributing/versioning.rst

These files **can** be changed if the examples are changed. However, they specifically reference the `7.1.0` API, so they can remain as they are if preferred (maybe a note added to clarify the fact).

source/spongineer/logs.rst
source/spongineer/debugging.rst

> Would it make more sense to have a dedicated version page that explained the format and have the install page reference that?

Yes, I think so. However, I believe the file `contributing/versioning.rst` should explain versioning with all other files pointing to it. People can contribute to the Sponge project in ways other than just coding. Even the server owner who does nothing more than just use the SpongeAPI contributes by establishing/maintaining a need or use for the project. And, versioning is a fundamental concept required by all. The server owner setting up a server, choosing plugins, or reporting an issue needs to understand versioning as much as a developer does. Therefore, it makes sense to me to explain versioning in the contributing section.

**Comment by ST-DDT** [comment]
From the server owner perspective you probably don't want to contribute if you want to get started (and thus are unfamiliar with the versions). So maybe we should use a dedicated top level page for the version overview.

**`source/versions.rst`**

* Compatibility overview
  * With a link to the respective download pages
  * With a link to creating a server and creating a plugin respectively
* Short explanation of our versioning policy (Semver)
* SpongeAPI versioning
* SpongeCommon/SpongeVanilla versioning
* SpongeForge versioning

**Comment by Grauldon** [comment]
I created a branch to start the changes, and I am using the above [comment from ST-DDT](https://github.com/SpongePowered/SpongeDocs/issues/768#issuecomment-457857782) as a guide. However, I read this [comment from Inscrutable](https://github.com/SpongePowered/SpongeForge/issues/2367#issuecomment-423096081) while reviewing the discussion. I just want to point this out to make sure we're all on the same page. I will continue the changes as mentioned above unless told otherwise.

**Comment by Grauldon** [comment]
Since [API-Versions](https://docs.spongepowered.org/stable/en/plugin/api-versions.html) is being updated, do we have new information for the API-Version table (e.g. update any TBA, add 7.2.0)?

**Comment by Inscrutable** [comment]
We can probably put API 7.0 as 'unsupported', as we already have a recommended builds for 7.1.X.
