### ISSUE TITLE
A spelling mistake in ZHCN page of plugin/configuration/index .

### ISSUE THREAD

**Issue by ExerciseBook** [SpongePowered/SpongeDocs#783]
![image](https://user-images.githubusercontent.com/6327311/51665780-84fbfa00-1ff7-11e9-8d9f-e85bb8d521a8.png)

It says
```
并通过 HoconConfigurationLoader 保存喂 HOCON。
```

The correct is
```
并通过 HoconConfigurationLoader 保存为 HOCON。
```

I did't find the repo of ZHCN page, so I can only post it here. 😂

**Comment by ST-DDT** [comment]
Our translations are created by the community using this page:
https://translate.spongepowered.org/
You can find the simplified chinese version here:
https://translate.spongepowered.org/project/sponge-docs/zh-CN#

Then search for the appropriate file there and suggest the change. Please note that you won't see the changes immediately, because the docs repo is only build when changes to the git repo are made.

If you don't want to change it there, please leave a comment here with the path of the file so we can report this to our other Chinese translators.

Thanks for bringing this to our attention.

**Comment by ST-DDT** [comment]
I moved your issue over to:

https://translate.spongepowered.org/project/sponge-docs/discussions/214

Please report all future translation issues directly on crowdin/our translation page.
