### ISSUE TITLE
Fix Ray Tracing documentation

### ISSUE THREAD

**Issue by NickAcPT** [SpongePowered/SpongeDocs#817]
In here, https://github.com/SpongePowered/SpongeDocs/blob/stable/source/plugin/ray-tracing.rst#L41, there's an error with the documentation of the `BlockRayBuilder#stopFilter` since it says following: 
```
The ``BlockRayBuilder#stopFilter`` stops the ray cast when it hits a block that passes the given filter [...]
```
According to dualspiral, a stop filter replaces/augments the distance filter and will only advance the ray while the result is true. Once it turns false, then the ray will not continue.
Instead of using the code provided in the documentation, in order to get ray casting working as the documentation describes, I had to use the following code:
```java
BlockRay<World> blockRay = BlockRay.from(p)
	.skipFilter(BlockRay.onlyAirFilter()).stopFilter(BlockRay.onlyAirFilter()).build();
```
That will stop when it hits a non air block.

###### dualspiral told me to open this issue.

**Comment by Grauldon** [comment]
The requested change necessitates a change in the explanation for the stopFilter method. Based on the original comment and the JavaDocs, the following statement:

> The BlockRayBuilder#stopFilter **stops** the ray cast when it hits a block that passes the given filter and the BlockRayBuilder#skipFilter skips all blocks that pass the filter. 

should read

> The BlockRayBuilder#stopFilter **continues** the ray cast when it hits a block that passes the given filter and the BlockRayBuilder#skipFilter skips all blocks that pass the filter. 

Otherwise, the code example contradicts the explanation. With the example given, the explanation says the trace stops when it encounters an air block. 

I am requesting a review by the @SpongePowered/developers team to ensure my proper understanding before making the changes. 

Note to self: Add a space between ``` convenience, ``` and ``` ``BlockRay`` ``` on line 44.

**Comment by JBYoshi** [comment]
https://github.com/SpongePowered/SpongeAPI/blob/b38390e1751fff802d355155c45b2eb4913f5817/src/main/java/org/spongepowered/api/util/blockray/BlockRay.java#L354-357

**Comment by ST-DDT** [comment]
@Grauldon Any update on this one?

**Comment by dualspiral** [comment]
It's been merged already, probably can be closed.

**Comment by Grauldon** [comment]
I'm sorry, @ST-DDT, for not responding. I adjusted some GitHub settings, so I didn't get an email about this. And, I haven't been on GitHub while I have been adjusting to a new job.
