### ISSUE TITLE
Redundant .pot Files pushed to Transifex

### ISSUE THREAD

**Issue by BlackGoat** [SpongePowered/SpongeDocs#96]
Files that are renamed or moved leave behind a ghost .pot file in the build sent to Transifex.
This is a problem because (i) it bloats storage, (ii) it wastes bandwidth, and importantly (ii) folk might translate redundant files. It isn't a severe issue, Transifex just has just too much *.pot.
Our esteemed @gratimax may have ideas for a solution.

**Comment by boformer** [comment]
(ii) and (ii)?

**Comment by gratimax** [comment]
There's no way to configure transifex to push only the updated files because there's simply no way to detect what has or has not updated. However, it's impossible to "translate redundant files" because all of the files that are uploaded are important. The translations are not overwritten, new translation strings are created if files are updated.
